la-mia-pizzeria-static/Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

la-mia-pizzeria-static/Models/MinWordsAttribute .cs
using System.ComponentModel.DataAnnotations;
namespace la_mia_pizzeria_static.Models
{
    public class MinWordsAttribute : ValidationAttribute
    {
        public int MinimumWords { get; set; }
        public MinWordsAttribute(int minimumWords)
        {
            this.MinimumWords = minimumWords;
        }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            string fieldValue = (string)value;

            var parole = fieldValue?.Split(' ');
            if (parole?.Where(s => s.Length > 0).Count() < MinimumWords)
            {
                return new ValidationResult($"Il campo deve contenere almeno {MinimumWords} parole");
            }

            return ValidationResult.Success;
        }
    }
}

la-mia-pizzeria-static/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using la_mia_pizzeria_static.Models;
using static System.Net.Mime.MediaTypeNames;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        [Key]
        public int PizzaId { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [MinWords(5)]
        public string Description { get; set; }
       
        //public IFormFile ImageFile { get; set; }
        public string? Image { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [Range(2, 50, ErrorMessage = "il prezzo deve essere tra 2 e 50 euro")]
        public double Price { get; set; }
        public Pizza() 
        {
          
        }
        public Pizza(string name, string description, string? image, double price)
        {
            Name = name;
            Description = description;
            Image = image ?? "~/img/Marghe-pizza-bufala.webp";
            Price = price;
        }
    }
}

la-mia-pizzeria-static/Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        private readonly ILogger<PizzaController> _logger;

        public PizzaController(ILogger<PizzaController> logger)
        {
            _logger = logger;
        }  
        
        public IActionResult Index()
        {
            return View(PizzaManager.GetPizzas());    
        }

        public IActionResult Details(int id)
        {
            var pizza = PizzaManager.GetPizza(id);
            if (pizza != null)
                return View(pizza);
            else
                return View("errore");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza data)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", data);
            }

            PizzaManager.InsertPizza(data);
           
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            // Prendo il post AGGIORNATO da database, non
            // uno passato da utente alla action
            var pizzaToEdit = PizzaManager.GetPizza(id);

            if (pizzaToEdit == null)
            {
                return NotFound();
            }
            else
            {
                return View(pizzaToEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Pizza data)
        {
            if (!ModelState.IsValid)
            {
                return View("Update", data);
            }

            // MODIFICA TRAMITE LAMBDA
            bool result = PizzaManager.UpdatePizza(id, pizzaToEdit =>
            {
                pizzaToEdit.Name = data.Name;
                pizzaToEdit.Description = data.Description;
                pizzaToEdit.Price = data.Price;
              //  pizzaToEdit.Image = data.Image;
            });

            if (result == true)
                return RedirectToAction("Index");
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (PizzaManager.DeletePizza(id))
                return RedirectToAction("Index");
            else
                return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

la-mia-pizzeria-static/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_MyLayout";

    Pizzeria mypizzeria = new Pizzeria("Pizzeria da Samu");
}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@mypizzeria.Name</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
    <body>
        <div class="container">
        <div class="d-flex justify-content-center"><img src="~/img/Da Samu.png" /></div>
            
            <div class="row">
                @foreach (var pizza in mypizzeria.pizzas)
                {
                    <div class="col-md-4">
                        <div class="pizza">
                            <img src="@Url.Content(pizza.Image)"/>
                            <h4 class="pt-3">@pizza.Name</h4>
                            <p>@pizza.Description</p>
                            <div class="ms-auto">@pizza.Price €</div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <style>
        .pizza {
            display: flex;
            flex-direction: column;
            height: 100%;
            padding: 15px;
        }

        .pizza img {
                width: 150px;
                height: 150px;
        }

        .pizza p {
                flex-grow: 1;
        }
        </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

la-mia-pizzeria-static/Views/Pizza/Create.cshtml
@model Pizza;
@{
    ViewData["Title"] = "Create Page";
    Layout = "_MyLayout";
}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzeria da Samu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container margin-top">
        <div class="row">
            <div class="col-md-6">
                <div class="d-flex justify-content-center">
                    <img src="~/svg/Create.svg" style="width: 80%; aspect-ratio:auto;" />
                </div>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-center">
                <form asp-controller="Pizza" asp-action="Create" method="post">
                    @Html.AntiForgeryToken()
                    <div class="mb-3">
                        <h2>Create your Unique Pizza</h2>
                        
                    </div>
                    <div class="mb-3">
                        <strong>Nome:</strong>
                        <input asp-for="Name" class="custom-form-control d-block w-100" type="text" />
                        <strong><span asp-validation-for="Name" class="text-muted"></span></strong>
                    </div>
                    <div class="mb-3">
                        <strong class="mb-2">Descrizione:</strong>
                        <textarea asp-for="Description" class="custom-form-control d-block w-100" style="resize: none; height: 60px;" rows="3" maxlength="1000"></textarea>
                        <strong><span asp-validation-for="Description" class="text-muted"></span></strong>
                    </div>
                     <div class="mb-3">
                        <strong>Immagine:</strong>
                        <input asp-for="Image" class="custom-form-control d-block w-100" type="text" />
                    </div> 
                    <div class="mb-3">
                        <div class="d-inline-block w-58">
                            <strong class="d-block">Prezzo:</strong>
                            <input asp-for="Price" type="number" class="custom-form-control w-100" />
                            <strong><span asp-validation-for="Price" class="text-muted"></span></strong>
                        </div>
                       
                        <div class="d-inline-block w-40 text-end">
                            <button type="submit" class="border-0 save-button">
                                <img src="~/svg/save.svg" style="width: 100px; aspect-ratio:auto;" />
                            </button>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
<style>
    .margin-top {
        margin-top: 75px;
    }

    .custom-form-control{
        padding: .3rem;
        background-color: #E3DCC9;
        font-weight: 400;
        line-height: 1.5;
        border: 1px solid black;
        border-radius: 5px;
    }
    .w-58{
        width: 58%;
    }
    .w-40{
        width: 40%;
    }

    .save-button{
        background: none;
    }
</style>
</html>

la-mia-pizzeria-static/Views/Pizza/Details.cshtml
@model Pizza
@{
    ViewData["Title"] = "Details Page";
    Layout = "_MyLayout";
}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center"><img style="width:250px; height:250px;" src="~/svg/Da Samu.svg" /></div>
        <div class="d-flex align-items-center justify-content-around mb-4">
            <a href="@Url.Action("Index", "Pizza")"><img style="width: 100px; aspect-ratio:auto;" src="~/svg/back-d.svg" /></a>
            <a href="@Url.Action("Update", "Pizza", new { id = Model.PizzaId })"><img style="width: 100px; aspect-ratio:auto;" src="~/svg/update-d.svg" /></a>
            <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@Model.PizzaId" method="post">
                @Html.AntiForgeryToken()
                <button type="submit" class="border-0 delete-button">
                    <img src="~/svg/delete-d.svg" style="width: 100px; aspect-ratio:auto;" />
                </button>
            </form>
        </div>

        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="pizza">
                    <img src="@Url.Content(Model.Image)" />
                    <h4 class="pt-3">@Model.Name</h4>
                    <p>@Model.Description</p>
                    <div>@Model.Price €</div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .pizza {
            display: flex;
            flex-direction: column;
            padding: 15px;
            text-align: center;
            align-items:center;
        }

            .pizza img {
                width: 200px;
                height: 200px;
                margin-bottom: 10px;
            }

            .pizza p {
                margin-bottom: 10px;
            }

        .delete-button{
            background:none;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

la-mia-pizzeria-static/Views/Pizza/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_MyLayout";
}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzeria da Samu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center align-items-center vh-100"><img style="width:80%; height:80%;" src="~/svg/Da Samu.svg" /></div>

        <div class="row">
            <h1 class="mb-2">Menù </h1>
            <p class="mb-4"> Il nostro impasto è preparato con ingredienti di alta qualità, selezionati con cura, e lievitato lentamente per oltre 48 ore. Questo processo garantisce una consistenza leggera e croccante, con una fragranza irresistibile, che esalta ogni boccone e rende ogni pizza un'esperienza unica e indimenticabile.</p>
            <hr />
            @foreach (var pizza in Model)
            {
                <div class="col-md-4">
                    <div class="pizza">
                        <img src="@Url.Content(pizza.Image)" />
                        <div class="d-flex">
                            <h4 class="pt-3">@pizza.Name</h4>
                            <a href="@Url.Action("Details", "Pizza", new { id = pizza.PizzaId })"><img style="width:20px; height:20px; margin: 10px;" src="~/img/eye.png" /></a>
                        </div>

                        <p>@pizza.Description</p>
                        <div class="ms-auto">@pizza.Price €</div>
                        
                    </div>
                </div>
            }
        </div>
    </div>
    <style>
        .pizza {
            display: flex;
            flex-direction: column;
            height: 100%;
            padding: 15px;
        }

            .pizza img {
                width: 150px;
                height: 150px;
            }

            .pizza p {
                flex-grow: 1;
            }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

la-mia-pizzeria-static/Views/Pizza/Update.cshtml
@model Pizza;
@{
    ViewData["Title"] = "Update Page";
    Layout = "_MyLayout";
}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzeria da Samu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container margin-top">
        <div class="row">
            <div class="col-md-6">
                <div class="d-flex justify-content-center">
                    <img src="~/svg/Update.svg" style="width: 80%; aspect-ratio:auto;" />
                </div>
            </div>
            <div class="col-md-6 d-flex flex-column justify-content-center">
                <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.PizzaId" method="post">
                    @Html.AntiForgeryToken()
                    <div class="mb-3">
                        <h2>Update your Amazing Pizza</h2>

                    </div>
                    <div class="mb-3">
                        <strong>Nome:</strong>
                        <input asp-for="Name" class="custom-form-control d-block w-100" type="text" />
                        <strong><span asp-validation-for="Name" class="text-muted"></span></strong>
                    </div>
                    <div class="mb-3">
                        <strong class="mb-2">Descrizione:</strong>
                        <textarea asp-for="Description" class="custom-form-control d-block w-100" style="resize: none; height: 60px;" rows="3" maxlength="1000"></textarea>
                        <strong><span asp-validation-for="Description" class="text-muted"></span></strong>
                    </div>
                    <div class="mb-3">
                        <strong>Immagine:</strong>
                        <input asp-for="Image" class="custom-form-control d-block w-100" type="text" />
                    </div> 
                    <div class="mb-3">
                        <div class="d-inline-block w-58">
                            <strong class="d-block">Prezzo:</strong>
                            <input asp-for="Price" type="text" class="custom-form-control w-100" />
                            <strong><span asp-validation-for="Price" class="text-muted"></span></strong>
                        </div>

                        <div class="d-inline-block w-40 text-end">
                            <button type="submit" class="border-0 update-button">
                                <img src="~/svg/opdatebutton.svg" style="width: 100px; aspect-ratio:auto;" />
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
<style>
    .margin-top {
        margin-top: 75px;
    }

    .custom-form-control {
        padding: .3rem;
        background-color: #E3DCC9;
        font-weight: 400;
        line-height: 1.5;
        border: 1px solid black;
        border-radius: 5px;
    }

    .w-58 {
        width: 58%;
    }

    .w-40 {
        width: 40%;
    }

    .update-button {
        background: none;
    }
</style>
</html>

la-mia-pizzeria-static/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

la-mia-pizzeria-static/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ovo&display=swap">
    <link rel="icon" href="~/img/favicon.svg" type="image/svg">
</head>
<body style="background: #E3DCC9">
    <header class="bg-black border-bottom box-shadow-3 fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm pb-1 pt-1 container">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Pizza" asp-action="Index"><img style="height: 50px; aspect-ratio:1;" src="~/img/logo.png"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> 
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link lightbeige" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link lightbeige" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link lightbeige" asp-area="" asp-controller="Pizza" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer class="border-custom footer ">
        <div class="container pt-2 pb-2">
            <span>&copy; 2024 - Pizzeria da Samu</span>
        </div>
    </footer>
</body>

<style>
    body {
        font-family: 'Ovo', sans-serif;
    }

    .nav-link.lightbeige {
        color: #E3DCC9;
        position: relative; 
        text-decoration: none;
    }

        .nav-link.lightbeige::after {
            content: '';
            position: absolute;
            left: 0;
            bottom: 0px;
            width: 0;
            height: 2px; 
            background-color: #ff0000;
            transition: width 0.5s ease; 
        }

        .nav-link.lightbeige:hover::after {
            width: 100%;
        }
        .border-custom{
        border-top: 1px solid #4B4B4B;
        color: #4B4B4B;
        }
</style>
</html>